### ISSUE TITLE
Merge csv files for testing

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-vision#82]
## 🚀 Feature
Complete csv file for testing

## Motivation

We have two csv's to test the wildfire dataset, we should put them together in one. This new csv must be as complete as possible to allow future tests.

**Comment by MateoLostanlen** [comment]
@frgfm We can discuss here the best strategy to build our test csv :)

**Comment by frgfm** [comment]
Thanks for opening it @MateoLostanlen!
So here is what I had in mind:
- if there need to be some content file for unittestting, it has to be small, and hardcoded (or properly generated) in the corresponding test script
- content files linked to the project should be in release attachments and be useful for users (not developers)

Otherwise with each different feature, we create a new content csv file specific for this test and end up with a messy git history. Sure it's not millions of lines, but still, on the last PR, there was a +2150 additions of which 2000 came from the csv. So I suggest we review the test and identify the specific cases we want to try out, and generate or hardcode the testing files (with pandas we can do this easily, and most of the information in the test file is not relevant for the test i.e. it could be randomly generated)

What do you think?
