### ISSUE TITLE
[models] Pretrained param loading design

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-vision#92]
There is currently no clear design for model checkpoint loading. Here is a proposal:
- [x] Data integrity: add the first 8 character of the SHA256 hash at the end of file name. Use this to check integrity upon download
- [x] Hosting: all pretrained models should be hosted on Github
- [x] File naming: each file should follow the naming convention architecture_imgsize-hash.pth (example: `resnet50_224-64cb5b95.pth`)
- [x] Architecture module: small suggestion https://github.com/frgfm/Holocron/blob/master/holocron/models/repvgg.py since this library is already in the dependencies

**Comment by MateoLostanlen** [comment]
We have one model for now (rexnet1_0x_acp_2e017f83.pth), I can change the name to add the image size https://github.com/pyronear/pyro-vision/releases.

In your name format there is no room for an extra comment ? for the model on the repo I added acp for adaptiveConcatPooling because it has a custom head.

**Comment by frgfm** [comment]
Mmmmh I suggest the extra comment to be put in architecture in the proposed naming so in your example it would yield:
`rexnet1_0x_acp_224_2e017f83` I guess?

**Comment by MateoLostanlen** [comment]
ok perfect

**Comment by frgfm** [comment]
Closed by #86
